language: python
sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_install:
  - pip3 install jsonschema
  - pip3 install requests
  - cd ..; git clone https://github.com/workflowhub/workflow-schema
  - cd pegasus-traces

script:
  - find . -type f -name "*.json" > traces.txt && err=0
  - for trace_file in `cat traces.txt`; do
      python3 ../workflow-schema/workflowhub-validator.py -d ${trace_file};
      (( err += $? ));
      echo "";
    done
  - if [ $err -ne 0 ]; then
      echo "The verification failed for ${err} trace files.";
      exit 1;
    fi
